title: zach churchill
author: Zach Churchill
email: zach.a.churchill@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  simple website for zach churchill that will be used for showing off all of
  the silly things he likes to keep track of.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zachchurchill.github.io"
github_username:  zachchurchill

# Build settings
theme: no-style-please
theme_config:
  appearence: "dark"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

plugins:
  - jekyll-feed
