title: zach churchill
author: Zach Churchill
email: website.trimness083@passmail.net
description: simple website to keep track of the silly things & write some thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zachchurchill.github.io"
github_username:  zachchurchill

theme:

plugins:
  - jekyll-postcss

postcss:
  cache: false
