title: zach churchill
author: Zach Churchill
email: contact@zachurchill.com
description: simple website to keep track of the silly things & write some thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zachchurchill.github.io"
github_username:  zachchurchill
cname: zachurchill.com

theme:

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  posts:
    permalink: /:collection/:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
